# Generated by Django 5.2.8 on 2026-05-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detections/')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('helmet', models.BooleanField(default=False)),
                ('gloves', models.BooleanField(default=False)),
                ('jacket', models.BooleanField(default=False)),
                ('shoes', models.BooleanField(default=False)),
                ('crack_detected', models.BooleanField(default=False)),
                ('status', models.CharField(default='PENDING', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
